/* deb-native: read the syscall catalog (src/syscalls.tsv) so dn-trace builds
 * its filter from the one list instead of hand-maintaining its own
 * (docs/spec/overlay.md, "The shared filter's rules"; principle 1).  The
 * build embeds the TSV verbatim as dn_catalog_tsv (syscall/dn-catalog.c,
 * generated by GNUmakefile), so dn-trace reads no file at run time.
 */
#ifndef DN_SYSCALLS_H
#define DN_SYSCALLS_H

#include <talloc.h>		/* TALLOC_CTX, */
#include "syscall/sysnum.h"	/* Sysnum, */

/* The catalog, verbatim (generated).  */
extern const char dn_catalog_tsv[];

/* Return, talloc'd on @context, the syscalls the filter may ALLOW when issued
 * from the gate page (catalog rows with gate=yes).  Returns 0, or -errno.  */
int dn_catalog_gate_sysnums(TALLOC_CTX *context, Sysnum **out, size_t *count);

#endif /* DN_SYSCALLS_H */
