#!/bin/sh
# Debian mode base environment (docs/debian-mode.md, "Base environment"):
# the one-time, idempotent preparation that must exist before any Debian
# package lands in Termux's prefix.
#
#   1. arm64 registered as a dpkg foreign architecture
#   2. $PREFIX/usr -> . (Debian's /usr/... paths resolve into the flat prefix)
#   3. runtime pieces: path shim, dn-run, update-alternatives wrapper
#   4. libc6:arm64 identity package: Termux's glibc under Debian's name
#
# Usage: dn-base-env.sh
set -eu
umask 022   # Termux defaults to 077; dpkg-deb rejects a 0700 DEBIAN/ dir
P=${PREFIX:-/data/data/com.termux/files/usr}
HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
MIRROR=${DN_DEBIAN_MIRROR:-https://deb.debian.org/debian}

# 1. foreign architecture
dpkg --print-foreign-architectures | grep -qx arm64 || dpkg --add-architecture arm64
echo "base-env: arm64 foreign architecture ok"

# 2. usr self-symlink
if [ -L "$P/usr" ]; then
  [ "$(readlink "$P/usr")" = . ] || { echo "base-env: $P/usr is a symlink, but not to '.'" >&2; exit 1; }
elif [ -e "$P/usr" ]; then
  echo "base-env: $P/usr exists and is not a symlink; refusing" >&2; exit 1
else
  ln -s . "$P/usr"
fi
echo "base-env: $P/usr -> . ok"

# 3. runtime pieces
"$HERE/fuse-runtime.sh" "$P"
echo "base-env: runtime (shim, dn-run, update-alternatives wrapper) ok"

# 4. libc6:arm64 identity package.
#
# Debian's own libc6 cannot run here: Android's app seccomp filter kills it
# at startup (set_robust_list -> SIGSYS). Termux's glibc is the same library
# with those syscalls patched out, so it is presented to dpkg AS libc6:arm64:
# a real package whose files are symlinks, at the exact paths Debian's libc6
# uses, into $PREFIX/glibc/lib. The file list is taken from Debian's real
# libc6 .deb and matched by soname. The version is the real Termux glibc
# version, so "libc6 (>= X)" still tells the truth; upgrades to Debian's own
# libc6 are blocked by the apt pin dn-mode.sh writes, not by the version.
GLIBC_LIB="$P/glibc/lib"
GV=$(dpkg-query -W -f='${Version}' glibc)
VERSION="${GV%%-*}-0dn1"
if [ "$(dpkg-query -W -f='${Version} ${db:Status-Abbrev}' libc6:arm64 2>/dev/null)" = "$VERSION ii " ]; then
  echo "base-env: libc6:arm64 $VERSION identity package already installed"
  exit 0
fi

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

# Debian's real libc6 .deb, only for its file list. Its Filename comes from
# whatever Debian index apt has (Debian mode lists), else the caller passes one.
REAL=${DN_LIBC6_DEB:-}
if [ -z "$REAL" ]; then
  FN=$(apt-cache show libc6:arm64 2>/dev/null | awk '/^Filename:/ {print $2; exit}')
  [ -n "$FN" ] || { echo "base-env: no Debian libc6 in the apt index; run dn-mode.sh debian && apt update, or set DN_LIBC6_DEB" >&2; exit 1; }
  REAL="$WORK/libc6-debian.deb"
  curl -fsSL -o "$REAL" "$MIRROR/$FN"
fi

PKG="$WORK/pkg"
LIBDIR="$PKG/lib/aarch64-linux-gnu"
mkdir -p "$PKG/DEBIAN" "$LIBDIR"
missing=""
for f in $(dpkg-deb -c "$REAL" | awk '{print $6}' | grep '^\./usr/lib/aarch64-linux-gnu/[^/]*[^/]$'); do
  so=${f##*/}
  if [ -e "$GLIBC_LIB/$so" ]; then
    ln -s "../../glibc/lib/$so" "$LIBDIR/$so"
  else
    missing="$missing $so"
  fi
done
[ -d "$GLIBC_LIB/gconv" ] && ln -s ../../glibc/lib/gconv "$LIBDIR/gconv"
ln -s aarch64-linux-gnu/ld-linux-aarch64.so.1 "$PKG/lib/ld-linux-aarch64.so.1"
# -L, not -e: the relative links only resolve once installed into $P.
[ -L "$LIBDIR/libc.so.6" ] && [ -L "$LIBDIR/ld-linux-aarch64.so.1" ] \
  || { echo "base-env: Termux glibc lacks libc.so.6 or the loader; is glibc installed?" >&2; exit 1; }

cat > "$PKG/DEBIAN/control" <<EOF
Package: libc6
Source: glibc
Version: $VERSION
Architecture: arm64
Multi-Arch: same
Section: libs
Priority: optional
Maintainer: deb-native <noreply@github.com>
Description: Termux glibc presented as Debian's libc6 (deb-native identity)
 Symlinks at Debian's libc6 paths into Termux's glibc ($GLIBC_LIB), which
 is patched for Android's seccomp filter; Debian's own libc6 is not.
 Generated by deb-native scripts/dn-base-env.sh.
EOF

# Never overwrite a file some other package (or nobody) owns.
(cd "$PKG" && find lib -type l) | while read -r rel; do
  t="$P/$rel"
  [ -e "$t" ] || [ -L "$t" ] || continue
  owner=$(dpkg -S "/$rel" 2>/dev/null | cut -d: -f1-2 | head -1)
  [ "$owner" = "libc6:arm64" ] || { echo "base-env: $t exists (owner: ${owner:-none}); refusing" >&2; exit 1; }
done

dpkg-deb -b --root-owner-group "$PKG" "$WORK/libc6_${VERSION}_arm64.deb" >/dev/null
dpkg --instdir="$P" --force-script-chrootless -i "$WORK/libc6_${VERSION}_arm64.deb"
[ -z "$missing" ] || echo "base-env: sonames Debian's libc6 has but Termux's glibc lacks (not linked):$missing"
echo "base-env: libc6:arm64 $VERSION identity package installed"
