#!/bin/sh
# Debian mode base environment (docs/debian-mode.md, "Base environment"):
# the one-time, idempotent preparation that must exist before any Debian
# package lands in Termux's prefix.
#
#   1. arm64 registered as a dpkg foreign architecture
#   2. $PREFIX/usr -> . (Debian's /usr/... paths resolve into the flat prefix)
#   3. runtime pieces, via main's setup-runtime.sh
#   4. libc6:arm64 identity package: Termux's glibc under Debian's name
#   5. tier-1 stand-ins: dn-dash, dn-debianutils, dn-openssl, dn-ca-certificates
#
# Usage: dn-base-env.sh
set -eu
umask 022   # Termux defaults to 077; dpkg-deb rejects a 0700 DEBIAN/ dir
P=${PREFIX:-/data/data/com.termux/files/usr}
HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
MIRROR=${DN_DEBIAN_MIRROR:-https://deb.debian.org/debian}

# 1. foreign architecture
dpkg --print-foreign-architectures | grep -qx arm64 || dpkg --add-architecture arm64
echo "base-env: arm64 foreign architecture ok"

# 2. usr self-symlink
if [ -L "$P/usr" ]; then
  [ "$(readlink "$P/usr")" = . ] || { echo "base-env: $P/usr is a symlink, but not to '.'" >&2; exit 1; }
elif [ -e "$P/usr" ]; then
  echo "base-env: $P/usr exists and is not a symlink; refusing" >&2; exit 1
else
  ln -s . "$P/usr"
fi
echo "base-env: $P/usr -> . ok"

# 3. runtime pieces -- main's own setup-runtime.sh, which places them under
# lib/deb-native/ when INSTDIR is Termux's prefix (scripts/dn-layout.sh):
# the shim, dn-run, the tracer, the dn-shell/dn-perl maintainer-script
# interpreter, no-op chown/chgrp/dpkg-statoverride, update-alternatives wrapper.
"$HERE/setup-runtime.sh" "$P"
# The shim maps a script's #!/bin/sh and #!/usr/bin/perl to
# "$INSTDIR/usr/bin/dn-shell" / "dn-perl" (main's layout). Those names are
# new in Termux's bin/, so plain links make main's path valid here too.
for n in dn-shell dn-perl; do
  [ -e "$P/bin/$n" ] && [ ! -L "$P/bin/$n" ] && { echo "base-env: $P/bin/$n exists and is not our link; refusing" >&2; exit 1; }
  ln -sfn "../lib/deb-native/fusion-bin/$n" "$P/bin/$n"
done
echo "base-env: runtime ($P/lib/deb-native, fusion-bin) ok"

# 4. libc6:arm64 identity package.
#
# Debian's own libc6 cannot run here: Android's app seccomp filter kills it
# at startup (set_robust_list -> SIGSYS). Termux's glibc is the same library
# with those syscalls patched out, so it is presented to dpkg AS libc6:arm64:
# a real package whose files are symlinks, at the exact paths Debian's libc6
# uses, into $PREFIX/glibc/lib. The file list is taken from Debian's real
# libc6 .deb and matched by soname. The version is the real Termux glibc
# version, so "libc6 (>= X)" still tells the truth; upgrades to Debian's own
# libc6 are blocked by the apt pin dn-mode.sh writes, not by the version.
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

build_libc6() {
  GLIBC_LIB="$P/glibc/lib"
  GV=$(dpkg-query -W -f='${Version}' glibc)
  VERSION="${GV%%-*}-0dn1"
  if [ "$(dpkg-query -W -f='${Version} ${db:Status-Abbrev}' libc6:arm64 2>/dev/null)" = "$VERSION ii " ]; then
    echo "base-env: libc6:arm64 $VERSION identity package already installed"
    return 0
  fi

  # Debian's real libc6 .deb, only for its file list. Its Filename comes from
  # whatever Debian index apt has (Debian mode lists), else the caller passes one.
  REAL=${DN_LIBC6_DEB:-}
  if [ -z "$REAL" ]; then
    FN=$(apt-cache show libc6:arm64 2>/dev/null | awk '/^Filename:/ {print $2; exit}')
    [ -n "$FN" ] || { echo "base-env: no Debian libc6 in the apt index; run dn-mode.sh debian && apt update, or set DN_LIBC6_DEB" >&2; exit 1; }
    REAL="$WORK/libc6-debian.deb"
    curl -fsSL -o "$REAL" "$MIRROR/$FN"
  fi

  PKG="$WORK/pkg"
  LIBDIR="$PKG/lib/aarch64-linux-gnu"
  mkdir -p "$PKG/DEBIAN" "$LIBDIR"
  missing=""
  for f in $(dpkg-deb -c "$REAL" | awk '{print $6}' | grep '^\./usr/lib/aarch64-linux-gnu/[^/]*[^/]$'); do
    so=${f##*/}
    if [ -e "$GLIBC_LIB/$so" ]; then
      ln -s "../../glibc/lib/$so" "$LIBDIR/$so"
    else
      missing="$missing $so"
    fi
  done
  [ -d "$GLIBC_LIB/gconv" ] && ln -s ../../glibc/lib/gconv "$LIBDIR/gconv"
  ln -s aarch64-linux-gnu/ld-linux-aarch64.so.1 "$PKG/lib/ld-linux-aarch64.so.1"
  # -L, not -e: the relative links only resolve once installed into $P.
  [ -L "$LIBDIR/libc.so.6" ] && [ -L "$LIBDIR/ld-linux-aarch64.so.1" ] \
    || { echo "base-env: Termux glibc lacks libc.so.6 or the loader; is glibc installed?" >&2; exit 1; }

  cat > "$PKG/DEBIAN/control" <<EOF
  Package: libc6
  Source: glibc
  Version: $VERSION
  Architecture: arm64
  Multi-Arch: same
  Section: libs
  Priority: optional
  Maintainer: deb-native <noreply@github.com>
  Description: Termux glibc presented as Debian's libc6 (deb-native identity)
   Symlinks at Debian's libc6 paths into Termux's glibc ($GLIBC_LIB), which
   is patched for Android's seccomp filter; Debian's own libc6 is not.
   Generated by deb-native scripts/dn-base-env.sh.
  EOF

  # Never overwrite a file some other package (or nobody) owns.
  (cd "$PKG" && find lib -type l) | while read -r rel; do
    t="$P/$rel"
    [ -e "$t" ] || [ -L "$t" ] || continue
    owner=$(dpkg -S "/$rel" 2>/dev/null | cut -d: -f1-2 | head -1)
    [ "$owner" = "libc6:arm64" ] || { echo "base-env: $t exists (owner: ${owner:-none}); refusing" >&2; exit 1; }
  done

  dpkg-deb -b --root-owner-group "$PKG" "$WORK/libc6_${VERSION}_arm64.deb" >/dev/null
  dpkg --instdir="$P" --force-script-chrootless -i "$WORK/libc6_${VERSION}_arm64.deb"
  [ -z "$missing" ] || echo "base-env: sonames Debian's libc6 has but Termux's glibc lacks (not linked):$missing"
  echo "base-env: libc6:arm64 $VERSION identity package installed"
}
build_libc6

# 5. Tier-1 Termux-backed stand-ins (docs/debian-mode.md, "Package tiers").
# A Debian name that an installed Termux package already fills: the
# stand-in is named dn-NAME (a package named NAME:arm64 would crossgrade
# Termux's NAME away), Provides NAME at the Termux version, and ships only
# links at Debian's paths into Termux's files. Debian's own NAME is pinned
# to -1 by dn-mode.sh.
#
# Path of $2 relative to directory $1 (same helper as normalize-symlinks.sh).
relpath() {
  awk -v from="$1" -v to="$2" 'BEGIN {
    nf = split(from, a, "/"); nt = split(to, b, "/"); i = 1
    while (i <= nf && i <= nt && a[i] == b[i]) i++
    out = ""
    for (j = i; j <= nf; j++) out = out (out == "" ? "" : "/") ".."
    for (j = i; j <= nt; j++) out = out (out == "" ? "" : "/") b[j]
    print (out == "" ? "." : out)
  }'
}

# standin NAME TERMUX_PKG [LINK=TARGET ...]   (paths relative to $P)
standin() {
  name=$1 tpkg=$2; shift 2
  v=$(dpkg-query -W -f='${Version}' "$tpkg" 2>/dev/null) \
    || { echo "base-env: $tpkg not installed; skipping dn-$name" >&2; return 0; }
  if [ "$(dpkg-query -W -f='${Version} ${db:Status-Abbrev}' "dn-$name:arm64" 2>/dev/null)" = "$v ii " ]; then
    echo "base-env: dn-$name $v already installed"; return 0
  fi
  pkg="$WORK/dn-$name"
  rm -rf "$pkg"; mkdir -p "$pkg/DEBIAN"
  for spec; do
    link=${spec%%=*} target=${spec#*=}
    [ -e "$P/$target" ] || { echo "base-env: dn-$name: $P/$target missing; not linked" >&2; continue; }
    mkdir -p "$pkg/$(dirname "$link")"
    ln -s "$(relpath "$P/$(dirname "$link")" "$P/$target")" "$pkg/$link"
    t="$P/$link"
    if [ -e "$t" ] || [ -L "$t" ]; then
      owner=$(dpkg -S "/$link" 2>/dev/null | head -1 | sed 's/: .*//')
      [ "$owner" = "dn-$name:arm64" ] || { echo "base-env: $t exists (owner: ${owner:-none}); refusing" >&2; exit 1; }
    fi
  done
  cat > "$pkg/DEBIAN/control" <<EOF
Package: dn-$name
Version: $v
Architecture: arm64
Provides: $name (= $v)
Section: admin
Priority: optional
Maintainer: deb-native <noreply@github.com>
Description: Termux's $tpkg presented as Debian's $name (deb-native stand-in)
 Satisfies Debian dependencies on $name with the installed Termux package
 $tpkg, which stays Termux's and is updated in Termux mode.
 Generated by deb-native scripts/dn-base-env.sh.
EOF
  dpkg-deb -b --root-owner-group "$pkg" "$WORK/dn-${name}_arm64.deb" >/dev/null
  dpkg --instdir="$P" --force-script-chrootless -i "$WORK/dn-${name}_arm64.deb" >/dev/null
  echo "base-env: dn-$name $v (Provides $name) installed"
}

standin dash dash
standin debianutils debianutils
standin ca-certificates ca-certificates \
  etc/ssl/certs/ca-certificates.crt=etc/tls/cert.pem
# Termux's "openssl" is the library; the CLI is openssl-tool. Debian's
# libssl3t64 looks for its CA bundle and config under /usr/lib/ssl, which
# Debian's openssl package provides as links into /etc/ssl. (After
# dn-ca-certificates, which creates etc/ssl/certs.)
standin openssl openssl-tool \
  lib/ssl/cert.pem=etc/tls/cert.pem \
  lib/ssl/certs=etc/ssl/certs \
  lib/ssl/openssl.cnf=etc/tls/openssl.cnf
