#!/bin/sh
# True fusion (docs/true-fusion.md): transform Termux's prefix, one way, into
# a Debian arm64 system. There is no switch back; the archive in
# ~/dn-fusion-backup/ is the only way to undo it. Idempotent: re-running
# regenerates every file.
#
#   1. snapshot Termux's floor (dn-floor.sh): never removed or crossgraded
#   2. Termux's sources moved aside (re-added later under multiarch rules)
#   3. Debian becomes apt's only source; tier-1 pins; the install pipeline
#   4. launchers first on PATH; Termux's `pkg` refuses (it rewrites sources)
#   5. apt update, then the base environment (dn-base-env.sh)
#
# Usage: dn-fuse.sh
set -eu
P=${PREFIX:-/data/data/com.termux/files/usr}
HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
STATE="$P/var/lib/deb-native"
APT="$P/etc/apt"

ls "$HOME"/dn-fusion-backup/termux-pkgstate-*.tar.gz >/dev/null 2>&1 \
  || { echo "dn-fuse: no backup in ~/dn-fusion-backup/ -- make one first" >&2; exit 1; }
mkdir -p "$STATE" "$P/etc/deb-native/termux-sources" "$APT/preferences.d" "$APT/apt.conf.d"

# 1. Floor, from Termux's state before anything below changes it.
[ -s "$STATE/floor" ] || "$HERE/dn-floor.sh" > "$STATE/floor"
echo "dn-fuse: floor: $(wc -l < "$STATE/floor") Termux packages"

# 2. Termux's sources, kept for phase 3 (Termux repos back under multiarch rules).
if grep -q 'termux' "$APT/sources.list" 2>/dev/null; then
  mv "$APT/sources.list" "$P/etc/deb-native/termux-sources/sources.list"
fi
for f in "$APT"/sources.list.d/*; do
  [ -e "$f" ] && mv "$f" "$P/etc/deb-native/termux-sources/"
done

# 3. Debian as the only source.
cat > "$APT/sources.list" <<EOF
# deb-native true fusion (scripts/dn-fuse.sh). Termux's own sources are in
# $P/etc/deb-native/termux-sources/.
deb [trusted=yes arch=arm64] https://deb.debian.org/debian stable main
deb [trusted=yes arch=arm64] https://deb.debian.org/debian stable-updates main
deb [trusted=yes arch=arm64] https://security.debian.org/debian-security stable-security main
EOF

# Tier 1: Debian names filled by Termux-backed packages (dn-base-env.sh) must
# never install from Debian: the glibc family dies under Android's seccomp
# filter, the others are floor packages and would be crossgraded away.
T1="libc6:arm64 libc-bin:arm64 libc6-dev:arm64 libc-dev-bin:arm64 libc-l10n:arm64 locales:arm64 dash:arm64 openssl:arm64 ca-certificates:arm64"
{
  for o in deb.debian.org security.debian.org; do
    printf 'Package: %s\nPin: origin %s\nPin-Priority: -1\n\n' "$T1" "$o"
  done
} > "$APT/preferences.d/deb-native"

cat > "$APT/apt.conf.d/99-deb-native" <<EOF
// deb-native true fusion (generated by scripts/dn-fuse.sh; docs/true-fusion.md).
Acquire::PDiffs "false";        // the index is rewritten after download
Acquire::Languages "none";
// main's apt-install.sh installs with --no-install-recommends.
APT::Install-Recommends "false";
APT::Update::Post-Invoke-Success { "$HERE/dn-debian-index.sh $P/var/lib/apt/lists"; };
// Packages are fused into the prefix (paths in a translated .deb are
// prefix-relative); maintainer scripts run without chroot (seccomp).
DPkg::Options:: "--instdir=$P";
DPkg::Options:: "--force-script-chrootless";
DPkg::Pre-Install-Pkgs { "$HERE/dn-hook-pre.sh"; };
DPkg::Tools::Options::$HERE/dn-hook-pre.sh "";
DPkg::Tools::Options::$HERE/dn-hook-pre.sh::Version "3";
DPkg::Post-Invoke { "$HERE/dn-hook-post.sh"; };
EOF

# 4. Launchers first on PATH (Termux's etc/profile sources profile.d).
cat > "$P/etc/profile.d/deb-native.sh" <<EOF
# deb-native true fusion (scripts/dn-fuse.sh): launchers for fused Debian programs
case ":\$PATH:" in *":$P/lib/deb-native/bin:"*) ;; *) export PATH="$P/lib/deb-native/bin:\$PATH" ;; esac
EOF
mkdir -p "$P/lib/deb-native/bin"
cat > "$P/lib/deb-native/bin/pkg" <<'EOF'
#!/system/bin/sh
echo "pkg: this prefix is fused into Debian (deb-native); Termux's pkg would rewrite apt's sources. Use apt." >&2
exit 1
EOF
chmod 755 "$P/lib/deb-native/bin/pkg"

# Leftovers of the earlier, reversible "Debian mode" experiment.
rm -f "$APT/apt.conf.d/99-dn-debian-mode" "$P/etc/profile.d/deb-native-debian-mode.sh"
rm -rf "$P/etc/deb-native/debian-mode" "$P/var/lib/apt/lists-debian"
cache=$(apt-config shell C Dir::Cache/d | sed "s/^C='\(.*\)'$/\1/")
rm -rf "$(dirname "$cache")/apt-debian"

# dn-debianutils was a stand-in in the reversible experiment; debianutils is
# not a floor package, so Debian's replaces Termux's outright now.
dpkg-query -W dn-debianutils:arm64 >/dev/null 2>&1 && dpkg --instdir="$P" --purge dn-debianutils:arm64

# 5. Debian index, then the base environment.
apt-get update
"$HERE/dn-base-env.sh"
echo "dn-fuse: done -- Debian is apt's only source; new shells get the launchers on PATH"
