#!/bin/sh
# Switch Termux's apt between stock Termux and Debian mode
# (docs/debian-mode.md). The switch is one file,
# $PREFIX/etc/apt/apt.conf.d/99-dn-debian-mode: present = Debian mode.
# Termux's own sources.list, sources.list.d/, lists and keys are never
# edited; Debian mode keeps its sources, lists and cache in its own paths.
#
# Usage: dn-mode.sh debian|termux|status
set -eu
P=${PREFIX:-/data/data/com.termux/files/usr}
HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
SWITCH="$P/etc/apt/apt.conf.d/99-dn-debian-mode"
ETC="$P/etc/deb-native/debian-mode"
LISTS="$P/var/lib/apt/lists-debian"
CACHE="$(dirname "$(apt-config shell C Dir::Cache/d | sed "s/^C='\(.*\)'$/\1/")")/apt-debian"

status() {
  if [ -f "$SWITCH" ]; then echo "mode: debian"; else echo "mode: termux"; fi
  apt-config dump | grep -E '^Dir::Etc::sourcelist |^Dir::State::lists ' || true
}

case "${1:-status}" in
  debian)
    # Idempotent: re-running regenerates every file (picks up changes here).
    ls "$HOME"/dn-fusion-backup/termux-pkgstate-*.tar.gz >/dev/null 2>&1 \
      || { echo "dn-mode: no backup in ~/dn-fusion-backup/ -- make one first" >&2; exit 1; }
    dpkg --print-foreign-architectures | grep -qx arm64 || dpkg --add-architecture arm64
    mkdir -p "$ETC/sources.list.d" "$ETC/preferences.d" "$LISTS/partial" "$CACHE/archives/partial"
    # Debian's own glibc family must never install: it dies under Android's
    # seccomp filter. libc6:arm64 is Termux's glibc (dn-base-env.sh).
    cat > "$ETC/preferences.d/dn-glibc" <<EOF
Package: libc6:arm64 libc-bin:arm64 libc6-dev:arm64 libc-dev-bin:arm64 libc-l10n:arm64 locales:arm64
Pin: origin deb.debian.org
Pin-Priority: -1

Package: libc6:arm64 libc-bin:arm64 libc6-dev:arm64 libc-dev-bin:arm64 libc-l10n:arm64 locales:arm64
Pin: origin security.debian.org
Pin-Priority: -1
EOF
    cat > "$ETC/sources.list" <<EOF
deb [trusted=yes arch=arm64] https://deb.debian.org/debian stable main
deb [trusted=yes arch=arm64] https://deb.debian.org/debian stable-updates main
deb [trusted=yes arch=arm64] https://security.debian.org/debian-security stable-security main
EOF
    cat > "$SWITCH.tmp" <<EOF
// deb-native Debian mode (generated by scripts/dn-mode.sh; docs/debian-mode.md).
// Delete this file (or run dn-mode.sh termux) to return to stock Termux.
Dir::Etc::SourceList "$ETC/sources.list";
Dir::Etc::SourceParts "$ETC/sources.list.d";
Dir::Etc::Preferences "$ETC/preferences";
Dir::Etc::PreferencesParts "$ETC/preferences.d";
Dir::State::Lists "$LISTS/";
Dir::Cache "$CACHE/";
Acquire::PDiffs "false";
Acquire::Languages "none";
APT::Update::Post-Invoke-Success { "$HERE/dn-debian-index.sh $LISTS"; };
// Install pipeline: packages are fused into Termux's prefix (paths inside
// a translated .deb are prefix-relative), maintainer scripts run without
// chroot (Android's seccomp forbids it). The pre hook gets apt's full plan
// (protocol version 3) to refuse any change to Termux's own packages, then
// translates each .deb; the post hook fixes the symlinks they brought in.
DPkg::Options:: "--instdir=$P";
DPkg::Options:: "--force-script-chrootless";
DPkg::Pre-Install-Pkgs { "$HERE/dn-hook-pre.sh"; };
DPkg::Tools::Options::$HERE/dn-hook-pre.sh "";
DPkg::Tools::Options::$HERE/dn-hook-pre.sh::Version "3";
DPkg::Post-Invoke { "$HERE/dn-hook-post.sh"; };
EOF
    mv "$SWITCH.tmp" "$SWITCH"
    echo "switched to debian mode; run: apt update"
    status ;;
  termux)
    rm -f "$SWITCH"
    echo "switched to termux mode (Debian lists kept in $LISTS)"
    status ;;
  status) status ;;
  *) echo "usage: dn-mode.sh debian|termux|status" >&2; exit 2 ;;
esac
