#!/bin/sh
# Build and install the prefix's stand-in packages (docs/design-0.2.0.md):
# real packages in the prefix's own dpkg database, under Debian's names,
# whose content is Termux's. Idempotent; re-run after Termux upgrades glibc,
# dpkg or apt to track their versions.
#
#   libc6  links at Debian's libc6 paths into Termux's glibc. Debian's own
#          libc6 is killed at startup by Android's seccomp filter
#          (set_robust_list -> SIGSYS); Termux's glibc is the same library
#          patched for Android at source level. File list taken from
#          Debian's real libc6 .deb, matched by soname. (From naibed's
#          dn-base-env.sh, nested paths.)
#   dpkg   the prefix's dpkg, dpkg-query, dpkg-deb, dpkg-split: launchers
#          running Termux's own with the prefix's admindir/instdir.
#   apt    the prefix's apt, apt-get, apt-cache, apt-mark, apt-config:
#          launchers running Termux's own with the prefix's APT_CONFIG.
#
# Versions are Termux's real ones ("<termux version>-0dn1"), so a Debian
# "Depends: libc6 (>= X)" still tells the truth. Debian's own libc6, dpkg
# and apt are pinned to -1 in the prefix (setup-apt-prefix.sh).
#
# Usage: dn-standins.sh PREFIX
set -eu
umask 022
DN=${1:?usage: dn-standins.sh PREFIX}
case "$DN" in /*) ;; *) DN="$PWD/$DN" ;; esac
TP=${DN_TERMUX_PREFIX:-${PREFIX:-/data/data/com.termux/files/usr}}
GLIBC_LIB="$TP/glibc/lib"
MIRROR=${DN_DEBIAN_MIRROR:-https://deb.debian.org/debian}
DPKG="$TP/bin/dpkg --admindir=$DN/var/lib/dpkg --instdir=$DN --force-not-root --force-script-chrootless"

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

ver() { v=$("$TP/bin/dpkg-query" -W -f='${Version}' "$1"); echo "${v%%-*}-0dn1"; }
installed() {  # PACKAGE VERSION
  [ "$("$TP/bin/dpkg-query" --admindir="$DN/var/lib/dpkg" -W -f='${Version} ${db:Status-Abbrev}' "$1:arm64" 2>/dev/null)" = "$2 ii " ]
}
control() {  # NAME VERSION MULTIARCH DESCRIPTION
  mkdir -p "$WORK/$1/DEBIAN"
  cat > "$WORK/$1/DEBIAN/control" <<EOF
Package: $1
Version: $2
Architecture: arm64
Multi-Arch: $3
Section: admin
Priority: optional
Maintainer: deb-native <noreply@github.com>
Description: $4 (deb-native stand-in)
 A deb-native stand-in: satisfies Debian dependencies on $1 with what
 Termux already provides. Generated by deb-native scripts/dn-standins.sh.
EOF
}
install_pkg() {  # NAME VERSION
  dpkg-deb -b --root-owner-group "$WORK/$1" "$WORK/$1_$2_arm64.deb" >/dev/null
  $DPKG -i "$WORK/$1_$2_arm64.deb" >/dev/null
  echo "standins: $1 $2 installed"
}
launcher() {  # PKGDIR NAME COMMAND...
  d=$1 n=$2; shift 2
  mkdir -p "$WORK/$d/usr/bin"
  printf '#!/system/bin/sh\n%s "$@"\n' "$*" > "$WORK/$d/usr/bin/$n"
  chmod 755 "$WORK/$d/usr/bin/$n"
}

# --- libc6 -------------------------------------------------------------
V=$(ver glibc)
if installed libc6 "$V"; then echo "standins: libc6 $V already installed"; else
  FN=$(APT_CONFIG="$DN/etc/apt.conf" "$TP/bin/apt-cache" show libc6:arm64 2>/dev/null | awk '/^Filename:/ {print $2; exit}')
  [ -n "$FN" ] || { echo "standins: Debian's libc6 is not in the prefix's apt index; run apt update first" >&2; exit 1; }
  curl -fsSL -o "$WORK/libc6-debian.deb" "$MIRROR/$FN"
  control libc6 "$V" same "Termux glibc presented as Debian's libc6"
  L="$WORK/libc6/usr/lib/aarch64-linux-gnu"
  mkdir -p "$L"
  missing=""
  for f in $(dpkg-deb -c "$WORK/libc6-debian.deb" | awk '{print $6}' | grep '^\./usr/lib/aarch64-linux-gnu/[^/]*[^/]$'); do
    so=${f##*/}
    if [ -e "$GLIBC_LIB/$so" ]; then ln -s "$GLIBC_LIB/$so" "$L/$so"; else missing="$missing $so"; fi
  done
  [ -d "$GLIBC_LIB/gconv" ] && ln -s "$GLIBC_LIB/gconv" "$L/gconv"
  ln -s aarch64-linux-gnu/ld-linux-aarch64.so.1 "$WORK/libc6/usr/lib/ld-linux-aarch64.so.1"
  [ -L "$L/libc.so.6" ] && [ -L "$L/ld-linux-aarch64.so.1" ] \
    || { echo "standins: Termux's glibc lacks libc.so.6 or its loader; is glibc installed?" >&2; exit 1; }
  install_pkg libc6 "$V"
  [ -z "$missing" ] || echo "standins: sonames Debian's libc6 has but Termux's glibc lacks (not linked):$missing"
fi

# --- dpkg --------------------------------------------------------------
V=$(ver dpkg)
if installed dpkg "$V"; then echo "standins: dpkg $V already installed"; else
  control dpkg "$V" foreign "Termux's dpkg, pointed at the prefix"
  A="--admindir=$DN/var/lib/dpkg"
  launcher dpkg dpkg "exec $TP/bin/dpkg $A --instdir=$DN --force-not-root --force-script-chrootless"
  launcher dpkg dpkg-query "exec $TP/bin/dpkg-query $A"
  launcher dpkg dpkg-deb "exec $TP/bin/dpkg-deb"
  launcher dpkg dpkg-split "exec $TP/bin/dpkg-split $A"
  install_pkg dpkg "$V"
fi

# --- apt ---------------------------------------------------------------
V=$(ver apt)
if installed apt "$V"; then echo "standins: apt $V already installed"; else
  control apt "$V" foreign "Termux's apt, pointed at the prefix"
  for n in apt apt-get apt-cache apt-mark apt-config; do
    launcher apt "$n" "APT_CONFIG=$DN/etc/apt.conf exec $TP/bin/$n"
  done
  install_pkg apt "$V"
fi
