#!/bin/sh
# Bootstrap a self-contained prefix (docs/design-0.2.0.md): a small, complete
# Debian root of its own -- its own apt/dpkg (Termux's, through stand-in
# launchers), database, libc6 and Debian base -- so installing into it is
# plain apt, as on Debian. Termux is never touched: everything lives under
# NEWPREFIX, and the prefix's apt reads only its own config.
#
#   1. directories, the prefix's dpkg database with arm64 as a foreign
#      architecture, Debian sources, pins, the prefix's apt.conf with the
#      install pipeline (dn-hook-pre.sh / dn-hook-post.sh)
#   2. runtime (shim, dn-shell, dn-run, privilege layer); $NEWPREFIX/root
#      linked to Termux's home
#   3. apt update (dn-debian-index.sh rewrites Architecture: all -> arm64)
#   4. stand-ins libc6, dpkg, apt (dn-standins.sh)
#   5. the Debian base through the prefix's own apt, then held
#   6. launchers, routing wrappers, PATH
#
# Usage: setup-apt-prefix.sh NEWPREFIX [debian-suite (default: stable)]
#
# KNOWN INSECURE SHORTCUT: sources.list uses [trusted=yes] -- Termux ships no
# Debian archive keyring. A signed deb-native repo is the next release's fix.
set -eu
NEWPREFIX=${1:?usage: setup-apt-prefix.sh NEWPREFIX [suite]}
case "$NEWPREFIX" in /*) ;; *) NEWPREFIX="$PWD/$NEWPREFIX" ;; esac
SUITE=${2:-stable}
HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
DN=$NEWPREFIX
TP=${DN_TERMUX_PREFIX:-${PREFIX:-/data/data/com.termux/files/usr}}

# Safety: never inside Termux's own prefix (that is the naibed branch's
# one-way transformation, not this).
case "$DN" in
  "$TP"|"$TP"/*)
    echo "setup-apt-prefix: refusing NEWPREFIX=$DN" >&2
    echo "  it is inside Termux's prefix ($TP); use a separate prefix, e.g. \$HOME/.dn." >&2
    exit 1 ;;
esac

# --- 1. database, sources, pins, apt.conf --------------------------------
# Only usr/* is created here: base-files ships bin, lib, sbin as links to
# usr/*, and its preinst refuses if they already exist as directories.
mkdir -p "$DN/etc/apt/apt.conf.d" "$DN/etc/apt/sources.list.d" \
         "$DN/etc/apt/preferences.d" "$DN/etc/apt/trusted.gpg.d" \
         "$DN/var/lib/apt/lists/partial" "$DN/var/cache/apt/archives/partial" \
         "$DN/var/lib/dpkg/updates" "$DN/var/lib/dpkg/info" "$DN/var/log/apt" \
         "$DN/usr/bin" "$DN/usr/lib"
[ -f "$DN/var/lib/dpkg/status" ] || : > "$DN/var/lib/dpkg/status"
[ -f "$DN/var/lib/dpkg/available" ] || : > "$DN/var/lib/dpkg/available"
touch "$DN/etc/apt/trusted.gpg"
"$TP/bin/dpkg" --admindir="$DN/var/lib/dpkg" --print-foreign-architectures | grep -qx arm64 \
  || "$TP/bin/dpkg" --admindir="$DN/var/lib/dpkg" --add-architecture arm64

cat > "$DN/etc/apt/sources.list" <<EOF
deb [trusted=yes arch=arm64] https://deb.debian.org/debian $SUITE main contrib non-free-firmware
deb [trusted=yes arch=arm64] https://deb.debian.org/debian ${SUITE}-updates main contrib non-free-firmware
deb [trusted=yes arch=arm64] https://security.debian.org/debian-security ${SUITE}-security main contrib non-free-firmware
EOF

# Debian's own copies of the stand-ins must never install: its libc6 dies
# under Android's seccomp filter, its dpkg/apt would replace the launchers.
# sudo/doas: setuid-root binaries that cannot work here; the names are kept
# for deb-native's own later (TODO.md, "sudo").
PINNED="libc6:arm64 libc-bin:arm64 libc6-dev:arm64 libc-dev-bin:arm64 libc-l10n:arm64 locales:arm64 dpkg:arm64 apt:arm64 sudo:arm64 doas:arm64"
for o in deb.debian.org security.debian.org; do
  printf 'Package: %s\nPin: origin %s\nPin-Priority: -1\n\n' "$PINNED" "$o"
done > "$DN/etc/apt/preferences.d/deb-native"

cat > "$DN/etc/apt.conf" <<EOF
// deb-native prefix (generated by scripts/setup-apt-prefix.sh; docs/design-0.2.0.md).
Dir::State "$DN/var/lib/apt";
Dir::State::status "$DN/var/lib/dpkg/status";
Dir::Cache "$DN/var/cache/apt";
Dir::Log "$DN/var/log/apt";
Dir::Etc "$DN/etc/apt";
Dir::Etc::sourcelist "$DN/etc/apt/sources.list";
Dir::Etc::sourceparts "$DN/etc/apt/sources.list.d";
Dir::Etc::trusted "$DN/etc/apt/trusted.gpg";
Dir::Etc::trustedparts "$DN/etc/apt/trusted.gpg.d";
Dir::Etc::preferences "$DN/etc/apt/preferences";
Dir::Etc::preferencesparts "$DN/etc/apt/preferences.d";
// Termux's dpkg is natively "aarch64"; Debian's packages stay arm64, a
// foreign architecture in the prefix's own database.
APT::Architectures { "aarch64"; "arm64"; };
APT::Install-Recommends "false";
Acquire::PDiffs "false";          // the index is rewritten after download
Acquire::Languages "none";
APT::Update::Post-Invoke-Success { "$HERE/dn-debian-index.sh $DN/var/lib/apt/lists"; };
Dpkg::Options:: "--instdir=$DN";
Dpkg::Options:: "--admindir=$DN/var/lib/dpkg";
Dpkg::Options:: "--force-not-root";
Dpkg::Options:: "--force-script-chrootless";
DPkg::Pre-Install-Pkgs { "$HERE/dn-hook-pre.sh $DN"; };
DPkg::Tools::Options::$HERE/dn-hook-pre.sh "";
DPkg::Tools::Options::$HERE/dn-hook-pre.sh::Version "3";
DPkg::Post-Invoke { "$HERE/dn-hook-post.sh $DN"; };
EOF
APT="env APT_CONFIG=$DN/etc/apt.conf $TP/bin/apt-get"

# --- 2. runtime, /root ----------------------------------------------------
"$HERE/setup-runtime.sh" "$DN"
# base-passwd's only user is root, home /root, and maintainer scripts write
# there: make it Termux's home (the shim rewrites /root into the prefix).
if [ ! -e "$DN/root" ] && [ ! -L "$DN/root" ]; then
  ln -s "$HOME" "$DN/root"
elif [ ! -L "$DN/root" ]; then
  echo "setup-apt-prefix: $DN/root exists and is not a link; leaving it" >&2
fi

# --- 3. index -------------------------------------------------------------
$APT update

# --- 4. stand-ins ---------------------------------------------------------
"$HERE/dn-standins.sh" "$DN"

# --- 5. Debian base, held -------------------------------------------------
# What every Debian package assumes is there: 0.1.x's bootstrap-base.sh set,
# plus Debian's Essential tools maintainer scripts call by name. Without them
# a script's `sed /etc/x` or `find /usr/...` falls through to Termux's Bionic
# tools, which the shim never reaches, and reads Android's real /etc
# (ca-certificates' postinst: "sed: can't read /etc/ca-certificates.conf",
# 0 certificates). ncurses-base: terminfo for Debian's ncurses.
# Three apt runs, because Essential packages are never declared as
# dependencies: apt would happily configure ca-certificates before sed is
# there. Within a run, dpkg's own Pre-Depends ordering applies (base-files
# needs awk first).
TOOLS="mawk coreutils sed grep findutils"
SYSTEM="base-files base-passwd dash debianutils diffutils gzip tar hostname ncurses-base ncurses-bin"
CONFIG="debconf cdebconf openssl ca-certificates"
$APT install -y $TOOLS
$APT install -y $SYSTEM
$APT install -y $CONFIG
BASE="$TOOLS $SYSTEM $CONFIG"
env APT_CONFIG="$DN/etc/apt.conf" "$TP/bin/apt-mark" hold $BASE >/dev/null
# The base is the prefix's own system, not programs for the user's shell:
# make-launchers.sh gives it no launchers, so Termux's ls/sed/grep stay first.
mkdir -p "$DN/var/lib/deb-native"
echo $BASE | tr ' ' '\n' > "$DN/var/lib/deb-native/base-packages"
echo "==> base installed and held: $(echo $BASE)"

# --- 6. launchers, routing, PATH ------------------------------------------
"$HERE/make-launchers.sh" "$DN"
"$HERE/make-apt-wrappers.sh" "$DN"
"$HERE/dn-activate.sh" "$DN"
echo "==> ready: apt install <package>   (Debian-only names go to $DN)"
