#!/bin/sh
# Build and install the prefix's stand-in packages (docs/spec/design-0.2.0.md):
# real packages in the prefix's own dpkg database, under Debian's names,
# whose content is Termux's. Idempotent; re-run after Termux upgrades glibc,
# dpkg or apt to track their versions.
#
#   libc6  links at Debian's libc6 paths into Termux's glibc. Debian's own
#          libc6 is killed at startup by Android's seccomp filter
#          (set_robust_list -> SIGSYS); Termux's glibc is the same library
#          patched for Android at source level. File list taken from
#          Debian's real libc6 .deb, matched by soname. (From naibed's
#          dn-base-env.sh, nested paths.)
#   dpkg   the prefix's dpkg, dpkg-query, dpkg-deb, dpkg-split: launchers
#          running Termux's own with the prefix's admindir/instdir.
#   apt    the prefix's apt, apt-get, apt-cache, apt-mark, apt-config:
#          launchers running Termux's own with the prefix's APT_CONFIG.
#
# Versions are Termux's real ones ("<termux version>-0dn1"), so a Debian
# "Depends: libc6 (>= X)" still tells the truth. Debian's own libc6, dpkg
# and apt are pinned to -1 in the prefix (setup-apt-prefix.sh).
#
# Usage: dn-standins.sh PREFIX
set -eu
umask 022
DN=${1:?usage: dn-standins.sh PREFIX}
case "$DN" in /*) ;; *) DN="$PWD/$DN" ;; esac
TP=${DN_TERMUX_PREFIX:-${PREFIX:-/data/data/com.termux/files/usr}}
GLIBC_LIB="$TP/glibc/lib"
MIRROR=${DN_DEBIAN_MIRROR:-https://deb.debian.org/debian}
DPKG="$TP/bin/dpkg --admindir=$DN/var/lib/dpkg --instdir=$DN --force-not-root --force-script-chrootless"

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

# <termux version>-0dnN; N counts changes to a stand-in's own content.
ver() { v=$("$TP/bin/dpkg-query" -W -f='${Version}' "$1"); echo "${v%%-*}-0dn${2:-1}"; }
# Fetch Debian's own copy of a package (pinned -1, never installed) for
# files the stand-ins take from it.
debian_deb() {  # PACKAGE OUTFILE
  fn=$(APT_CONFIG="${DN_APT_CONFIG:-$DN/etc/apt.conf}" "$TP/bin/apt-cache" show "$1:arm64" | awk '/^Filename:/ {print $2; exit}')
  [ -n "$fn" ] || { echo "E: Debian's $1 is not in the prefix's apt index; run apt update first" >&2; exit 1; }
  curl -fsSL -o "$2" "$MIRROR/$fn"
}
installed() {  # PACKAGE VERSION
  [ "$("$TP/bin/dpkg-query" --admindir="$DN/var/lib/dpkg" -W -f='${Version} ${db:Status-Abbrev}' "$1:arm64" 2>&1)" = "$2 ii " ]
}
control() {  # NAME VERSION MULTIARCH DESCRIPTION
  mkdir -p "$WORK/$1/DEBIAN"
  cat > "$WORK/$1/DEBIAN/control" <<EOF
Package: $1
Version: $2
Architecture: arm64
Multi-Arch: $3
Section: admin
Priority: optional
Maintainer: deb-native <noreply@github.com>
Description: $4 (deb-native stand-in)
 A deb-native stand-in: satisfies Debian dependencies on $1 with what
 Termux already provides. Generated by deb-native scripts/dn-standins.sh.
EOF
}
install_pkg() {  # NAME VERSION
  echo "Building stand-in $1:arm64 ($2) ..."
  dpkg-deb -b --root-owner-group "$WORK/$1" "$WORK/$1_$2_arm64.deb"
  $DPKG -i "$WORK/$1_$2_arm64.deb"
}
launcher() {  # PKGDIR NAME COMMAND...
  d=$1 n=$2; shift 2
  mkdir -p "$WORK/$d/usr/bin"
  # $DN/usr/bin ahead of PATH: dpkg/apt (Termux's own, per the docstring
  # above) spawn maintainer scripts that inherit this PATH. Without it,
  # a plain `sed`/`find`/`grep` in a postinst resolves to Termux's Bionic
  # build (on the interactive shell's PATH, per dn-activate.sh) instead of
  # the prefix's own Debian glibc ones -- Bionic binaries aren't behind the
  # shim's LD_PRELOAD interposition, so they can't see the prefix's rewritten
  # paths (e.g. ca-certificates' postinst: "sed: can't read
  # /etc/ca-certificates.conf", TODO.md "Quick wins"). $DN/usr/bin is
  # deliberately off the *interactive* PATH (make-launchers.sh) so it must
  # not shadow Termux's own tools there; scoping it to just these wrappers'
  # child processes keeps that intact.
  printf '#!/system/bin/sh\nPATH="%s/usr/bin:%s/usr/sbin:$PATH"\n%s "$@"\n' \
    "$DN" "$DN" "$*" > "$WORK/$d/usr/bin/$n"
  chmod 755 "$WORK/$d/usr/bin/$n"
}

# --- libc6 -------------------------------------------------------------
V=$(ver glibc)
if installed libc6 "$V"; then echo "libc6:arm64 is already the newest version ($V)."; else
  # The bootstrap has no prefix apt config yet: it passes its temporary one.
  debian_deb libc6 "$WORK/libc6-debian.deb"
  control libc6 "$V" same "Termux glibc presented as Debian's libc6"
  L="$WORK/libc6/usr/lib/aarch64-linux-gnu"
  mkdir -p "$L"
  missing=""
  for f in $(dpkg-deb -c "$WORK/libc6-debian.deb" | awk '{print $6}' | grep '^\./usr/lib/aarch64-linux-gnu/[^/]*[^/]$'); do
    so=${f##*/}
    if [ -e "$GLIBC_LIB/$so" ]; then ln -s "$GLIBC_LIB/$so" "$L/$so"; else missing="$missing $so"; fi
  done
  [ -d "$GLIBC_LIB/gconv" ] && ln -s "$GLIBC_LIB/gconv" "$L/gconv"
  ln -s aarch64-linux-gnu/ld-linux-aarch64.so.1 "$WORK/libc6/usr/lib/ld-linux-aarch64.so.1"
  [ -L "$L/libc.so.6" ] && [ -L "$L/ld-linux-aarch64.so.1" ] \
    || { echo "E: Termux's glibc lacks libc.so.6 or its loader; is glibc installed?" >&2; exit 1; }
  install_pkg libc6 "$V"
  [ -z "$missing" ] || echo "W: Termux's glibc lacks these libc6 sonames (not linked):$missing"
fi

# --- dpkg --------------------------------------------------------------
V=$(ver dpkg 3)
if installed dpkg "$V"; then echo "dpkg:arm64 is already the newest version ($V)."; else
  control dpkg "$V" foreign "Termux's dpkg, pointed at the prefix"
  A="--admindir=$DN/var/lib/dpkg"
  launcher dpkg dpkg "exec $TP/bin/dpkg $A --instdir=$DN --force-not-root --force-script-chrootless"
  launcher dpkg dpkg-query "exec $TP/bin/dpkg-query $A"
  launcher dpkg dpkg-deb "exec $TP/bin/dpkg-deb"
  launcher dpkg dpkg-split "exec $TP/bin/dpkg-split $A"
  # Termux's dpkg lacks dpkg-maintscript-helper, which many Debian packages'
  # scripts call to move or remove old conffiles (debian-archive-keyring's
  # preinst: "dpkg-maintscript-helper: command not found"). Debian's own is
  # a shell script, DPKG_ROOT-aware, calling dpkg/dpkg-query by name --
  # which in a maintainer script are the prefix's launchers above.
  debian_deb dpkg "$WORK/dpkg-debian.deb"
  # It loads one library file of its own, /usr/share/dpkg/sh/dpkg-error.sh
  # (which the shim maps into the prefix): ship both.
  dpkg-deb --fsys-tarfile "$WORK/dpkg-debian.deb" | tar -x -C "$WORK/dpkg" \
    ./usr/bin/dpkg-maintscript-helper ./usr/share/dpkg/sh/dpkg-error.sh
  install_pkg dpkg "$V"
fi

# --- apt ---------------------------------------------------------------
V=$(ver apt)
if installed apt "$V"; then echo "apt:arm64 is already the newest version ($V)."; else
  control apt "$V" foreign "Termux's apt, pointed at the prefix"
  for n in apt apt-get apt-cache apt-mark apt-config; do
    launcher apt "$n" "APT_CONFIG=$DN/etc/apt.conf exec $TP/bin/$n"
  done
  install_pkg apt "$V"
fi
